### ISSUE TITLE
Selecting audio playback device

### ISSUE THREAD

**Issue by newasf** [skuethe/MMM-Spotify#126]
My audio is set to bt for my pi, but for some reason mmm-spotify plays through the monitor. I'm assuming this is because hdmi is selected for audio in raspi-config, as bt isn't an option there..I'm VERY new to all this, but is there a way to access and adjust this playback option for mm-spotify? Thank you!

**Comment by skuethe** [comment]
Hey there, as this was / is your first ever issue on github I am not sure if it was intentional to directly closed the issue after creating it. So I'll just give you feedback anyways :)

Unfortunately there is no option in MMM-Spotify to control sound output. Everything what is being displayed is handled by Spotify itself. So all the available playback devices are taken from your Spotify account and listed here for selection.

**Comment by newasf** [comment]
I did close it purposely actually because I remembered I had a different module for the audio. (I'm attempting to restart a build based on bookmarks and memory lol) Thank you for the response though, it can be intimidating to post questions on here when you're new. >.<
