### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by artomka** [skuethe/MMM-Spotify#142]
Hi, I cannot solve a weird problem: The logo of Spotify is always visible. When I play music, the logo changes to the player correctly. However, when I stop playing, the logo shows again. Do you know, how to solve it, please? I have fresh installed MM and Spotify-MMM module.

Thanks.

**Comment by skuethe** [comment]
Hello. This is not a weird problem. It was already like this before, but was bugged. It got fixed in the latest version.
Currently there is no option to hide the logo if nothing is playing. You have two options here:

1. wait for / work on a PR to implement a new config option which can control the image being hidden
2. checkout the specific git version which still had the "old" behaviour

If you go nr. 2 however, you will not receive updates in the future without switching back to the default git branch.
Do this by switching to the MMM-Spotify directory, and executing `git fetch` followed by a `git checkout v1.6.3`.

**Comment by artomka** [comment]
Ok :) I did not know about it. Thank you for the response. I will wait for your update :)

**Comment by fantasyflip** [comment]
Late to the party but for any future visitors here's a solution that works for me using custom CSS:

```css
img[src="./modules/MMM-Spotify/resources/spotify-xxl.png"] {
  display: none;
}
```

It hides the img-tag that contains album covers and the spotify logo only if the spotify logo is visible.
