### ISSUE TITLE
MMM-Spotify doesn't work

### ISSUE THREAD

**Issue by sazizah** [skuethe/MMM-Spotify#161]
I have followed step by step to install this module but it doesn't work on my magic mirror with an error :
"Failed to fetch git data for MMM-Spotify: Error: block timeout reached"
how should i fix it?

**Comment by skuethe** [comment]
Thank you for opening an issue here. This error seems to be connected to a node module used in MM².
A quick search pointed me to [this current issue](https://github.com/MichMich/MagicMirror/issues/1907).

So it seems to be related to zombie processes which are trying to update the module, but fail to do so on time (without reading to much into it). So my first suggestion would be:
1. try to restart your PI and see if that helps (= zombie processes are gone)
2. otherwise there seems to be a workaround by increasing some timeout value - see [this command](https://github.com/MichMich/MagicMirror/issues/1907#issuecomment-823637387)

**Comment by skuethe** [comment]
Please let me know if that information has helped.
Otherwise please share some more information from the MM² log output.
Also make sure you are running the latest MM² version (`2.15.0`)

**Comment by sazizah** [comment]
thank you so much for your help, I've tried to restart the PI, but the results are the same.  i tried changing the timeout to `15000` it fix the error `Failed to fetch git data for MMM-Spotify: Error: block timeout reached`.
but if i ask to the mirror to play a song it didn't respond

**Comment by skuethe** [comment]
Okay, like I said, for more information I would need the log of MM² to see whats going on. Make sure that no sensitive information are present in the log output (like API keys, passwords etc.) before sharing.

**Comment by skuethe** [comment]
I will close this issue for now. Feel free to re-open / comment on it when you have gathered the log file for further debugging.
