### ISSUE TITLE
Can only see white spotify logo after update

### ISSUE THREAD

**Issue by Cam9731** [skuethe/MMM-Spotify#164]
Hello, I got a new internet provider today and as such some of my modules were broken. Because of this I decided that I may as well update all of them as i'm already at it. 

Anyways, while updating, it seems that i've somehow broken the module to the point where I can only see the white spotify logo and the change profile button. I'm not sure what caused this issue and i've tried everything I can think of including using a fresh config file as well as recreating the api on the spotify dashboard. FirstAuth also seems to successfully create the tokens. I also do have premium as well.

I'm pretty stumped here guys, let me know if you have any ideas or input!

Thanks,

Cam

![image](https://user-images.githubusercontent.com/55032379/117749198-f109c880-b1d6-11eb-932d-198f151d216d.png)

**Comment by skuethe** [comment]
Hey there,
thank you for opening this issue.

Some first feedback on the information you provided:
- Showing that Spotify logo is the default "idle" behaviour from this module, so that by itself is not a problem
- Switching / updating versions should not break any functionality, with an possible exception of the `mini` styled view


To actually help you, I need some more information:
- Do you know from which version you updated?
- Please provide your `MMM-Spotify` related configuration - make sure you remove any sensitive information which could be present before pasting it here
- Please restart MM² and provide the application logs - make sure you remove any sensitive information / data before pasting it here

Without more insights this screenshot just seems to be working as intended.
Looking forward for your input.

**Comment by DavidD303** [comment]
is there a way to hide the logo when nothing is being played?

**Comment by skuethe** [comment]
There is no such configuration option. You could create a PR or fiddle around with overwriting the specific CSS

**Comment by skuethe** [comment]
It's been three months without a reply. I'll go ahead and close the issue.
If you have any updates, feel free to re-open the ticket.
