### ISSUE TITLE
ONSTART race condition?

### ISSUE THREAD

**Issue by ackzell** [skuethe/MMM-Spotify#48]
Hello @eouia !

Thanks for this amazing module. My brother is building a mirror and this is just what he wanted.

I think we found a little issue where the code in https://github.com/eouia/MMM-Spotify/blob/313357226f335446c145e10a4c5b419326356125/node_helper.js#L100
doesn't know what `this.spotify` is.

We realized that it takes a bit for `this.spotify` to be defined when implementing the `onStart` option configuration. (It would never execute that part even if the config was present).

We were on a screenshare and I didn't have a chance to properly debug, but what we ended up doing was adding a `timeout` in there (I think it was a 1000ms) and after that we went and implemented the rest of the flow as it was in the helper. This "fixed" our issue, but certainly not the most elegant (nor appropriate) solution to it.

I could try to reproduce in a local environment in the future, I also find it weird that this hasn't been reported previously. 

But anyhow, we wanted to let you know we found this just in case you wanted to take a look.

Thanks again and keep up the good work!

**Comment by eouia** [comment]
I'll inspect. If possible, Your PR would be helpful to others.

**Comment by djdocta** [comment]
@ackzell 
Could you please post what you've done exactly ? This could be a good option for me for another issues I'm facing. 
Thanks.

**Comment by ackzell** [comment]
Thanks @eouia 
I don't have the environment handy, so a PR in the near future is not realistic for me. 

@djdocta I can't provide a proper diff since I don't have the changes physically with me, also like I said this is *not* what I would consider the appropriate solution, but here it goes:

Changes go around this line of code:
https://github.com/eouia/MMM-Spotify/blob/313357226f335446c145e10a4c5b419326356125/node_helper.js#L101

Notice we are creating a timeout when the notification is `"ONSTART"` and just letting the rest of the flow to happen so that when 1sec has passed, `this.spotify` will actually be defined and we can continue executing the logic that was already there.

```js
if (noti == "ONSTART") {
                setTimeout(() => {
                        if (this.spotify) {
                                payload.position_ms = 0
                                if (payload.search) {
                                    var param = {
                                        q: payload.search.keyword,
                                        type: payload.search.type,
                                    }
                                    var condition = {
                                        random: payload.search.random,
                                        autoplay: true,
                                    }
                                    this.searchAndPlay(param, condition)
                                } else if (payload.spotifyUri.match("track")) {
                                    this.spotify.play({uris: [payload.spotifyUri]})
                                } else if (payload.spotifyUri) {
                                    this.spotify.play({context_uri: payload.spotifyUri})
                                }
                                if (payload.deviceName) this.spotify.transferByName(payload.deviceName)
                        }
                }, 1000)
        }
```

**Comment by djdocta** [comment]
@ackzell 
Thanks for the feedback.
Printout of the log indeed show the valur « null » for this.spotify.
I will do some more tests and get back at you.

**Comment by djdocta** [comment]
@ackzell, 
INIT and ONSTART are not really racing, they are even partners :-) (they are launched almost at the same time).
In fact, the way MMM-Spotify is coded today, during initialization step (by definition : INIT),  the program will (in order to create an instance of "this.spotify") loop until he founds a playing device.   
That means that in order "this.spotify" to be initialized during **startup** (by definition : ONSTART), an external Spotify client should be already playing music (at best even BEFORE you launch your mirror). Setting a timeout on the ONSTART is a good workaround but it shouldn't be necessary as long the above condition are respected (the only case it could be necessary for me is if there is/was already a delay (of playing music) during initialization. 
But this all gave me a hint an order to solve my own issue :-)

@eouia,
you probably remember this issue #341 of AssistantMK2 : [ https://github.com/bugsounet/MMM-AssistantMk2/issues/341 ](url)  
In fact it is impossible AS IS to ask the execution of a vocal notification via MMM-Spotify without launching first an external client (computer,phone ...).  What I wanted to do was to ask my mirror to launch a song directly (on my RASPOTIFY account for ex.) without the inconvenience of using an external client. Because of what was explained to @ackzell, it was not possible as the initialization step is doing the following loop as long as nothing is played : 
INIT => findCurentSpotify => getTrackPlaying => INIT =>  findCurentSpotify etc... 

What I did, was : 

- In order to exit the initialization loop : modify the code in order to fill "this.spotify" even if no song is playing (the element spotify is indeed know as config and all other elements are already declared). 
In reality, the loop will continue but the initialization will allow the exit of the loop/parallel treatment of other notification at a given time.  

- In order to be able play a song (or manipulate the spotify client), the SPOTIFY WEB API needs to have an ACTIVE device so I had to change the code so that, first, I could retrieve the list of all devices for my spotify client (https://api.spotify.com/v1/me/devices), then transfer the users playback to this device (https://api.spotify.com/v1/me/player - this trick will indeed turn your device to be ACTIVE), and finaly ask for playing of the the song on that specific device (https://api.spotify.com/v1/me/player/play).

All tools were already available, the code just needed some small changes (node_helper and Spotify.js ) in order to use them in a better/different way....maybe not everyone's problem but for me it was a MUST...and it WORKS like  charm ... certainly some fine tuning to do but for now it is exactly what I wanted and I don't need my phone or computer anymore to start Spotify on my mirror. 
So @eouia, issue #341 can be closed. 

Thanks.

**Comment by bugsounet** [comment]
i will rewrite `onStart` condition to start
it will be executed after loading...
so ... just after this log:
`[SPOTIFY] Started` ... everything is started and can play onStart

**Comment by bugsounet** [comment]
ok, it's coded in the `dev` branch
just wait next update :)

**Comment by bugsounet** [comment]
v1.3.2 with corrected code ;)

tell me if ok for you ?

**Comment by djdocta** [comment]
@bugsounet 
Thanks for the update, the code is much much clearer now. 
If I can just add 2 small remarks : 

1. Below code is obsolete in node_helper.js (function searchAndPlay): 
    if (this.spotify == null) {
      this.findCurrentSpotify()
      return
    }
function findCurrentSpotify() has been removed/integrated/replaced by initAfterLoading, so therefore this call should be removed.  And on top of that, I might be wrong, but this.spotify should never be equal to null at this point (as it should have been populated during loading process (if presence of config file)).

2.  Same remark as before, Spotify will never (almost never) play a song during ONSTART, if "transfer" notification is not launched on that specific device before "play" notification.  

Merci.

**Comment by bugsounet** [comment]
1) oupss ... i will correct it with 1.4.1
2)  i don't think to that condition, i will do it
Note : i have do it with A2D and native response (transfer and play), 
so i will do it in `ONSTART` code too

**Comment by bugsounet** [comment]
So:

1) i correct it [there](https://github.com/bugsounet/MMM-Spotify/pull/83/commits/7065c4853c1c2613cd9161f8bbf95b54d1571749)
2) Work correctly now with [this](https://github.com/bugsounet/MMM-Spotify/pull/83/commits/dd087cb3afe4d00efc73689888296601ef0b2982)

**Comment by djdocta** [comment]
Good job. Thanks.
This will avoid me doing manual update of the code everytime I do a git pull. 😄😁

**Comment by bugsounet** [comment]
We have some minor fix to do and we push it to master

**Comment by bugsounet** [comment]
pushed to master

**Comment by djdocta** [comment]
Great work.

**Comment by bugsounet** [comment]
perfect ;)

I close this issue
