### ISSUE TITLE
Stuck on authentication

### ISSUE THREAD

**Issue by KSGulin** [skuethe/MMM-Spotify#88]
Hi,

my process is getting stuck on authentication. When I run 

`node first_auth.js`

I get the output 

`[SPOTIFY] Initialized`

and then the process just freezes. I've double checked all the steps and tried again from scratch, but get the same result each time.

**Comment by bugsounet** [comment]
[retry with RPI desktop in a terminal](https://github.com/bugsounet/MMM-Spotify#install)

**Comment by GabrielNoga** [comment]
Hello,
I had the same problem, because I was connecting through SSH.
When you run `node first_auth.js` it will open the browser to put your credentials.
Connect to a display or install xrdp, then you can connect through Windows Remote Desktop Connection.

If you are using the Raspberry Pi OS Lite you need to install the GUI, I've installed the LXDE.

**Comment by bugsounet** [comment]
hi, it's writed on [ReadMe](https://github.com/bugsounet/MMM-Spotify#4-get-auth) ;)

>If you are using the Raspberry Pi OS Lite you need to install the GUI, I've installed the LXDE.

see MagicMirror install [guide](https://docs.magicmirror.builders/getting-started/requirements.html#requirements)

**Comment by GabrielNoga** [comment]
I didn't get that at the time hahaha, thanks

**Comment by bugsounet** [comment]
no problem ;)
happy use !
