### ISSUE TITLE
Control of Sonos devices ....

### ISSUE THREAD

**Issue by jamesvcc** [skuethe/MMM-Spotify#92]
Hi, I have this up and running and its great. However, I can use this module fine to control Spotify connect on most of the devices I have - except Sonos speakers.

If I choose a Sonos speaker as an output (Spotify Connect) device then the module will no longer start/stop/skip/reverse etc... through the playlist. If I then choose a different type of output device then control comes back again.

Seems to be that it does not like controlling Connect devices that are Sonos. Any ideas?

**Comment by bugsounet** [comment]
Hi,
sorry, I can't debug because i have no Sonos device

**Comment by jamesvcc** [comment]
Hi – can I help you in any way?

Regards,

James Currie-Cathey

**Comment by skuethe** [comment]
@jamesvcc :
This module is not controling your speakers directly. It is just communicating with the Spotify API.
So if your device is not controllable when selected, there maybe a general problem with Sonos devices and Spotify?

As this issue is a bit older, did you try to update software on the Sonos devices? (if that is a thing - I do not own any Sonos)

**Comment by deb42** [comment]
Hi all,

this is a know issue with the Spotify implementation in Sonos devices:

https://community.spotify.com/t5/Spotify-for-Developers/Spotify-Connect-Devices-WEB-API/td-p/5005888
https://github.com/spotify/web-api/issues/525

Unfortunatly, Sonos devices are not displayed with the Spotify API.

**Comment by skuethe** [comment]
Thanks for letting me know @deb42 !
